# Seri haberleşme
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

# UART Interrupt sürücüsü 
CONFIG_UART_INTERRUPT_DRIVEN=y

# ADC sürücüsü
CONFIG_ADC=y

# I2C sürücüsü
CONFIG_I2C=y

# Metin için gerekliymiş
CONFIG_CBPRINTF_FP_SUPPORT=y

# GÜÇ YÖNETİMİ AYARLARI
CONFIG_PM=y
CONFIG_PM_DEVICE=y
CONFIG_PM_POLICY_CUSTOM=n
