CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_ADC=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_SERIAL=y
CONFIG_PRINTK=y
CONFIG_CBPRINTF_FP_SUPPORT=y

# Düşük Güç ve Otomatik Zamanlayıcı
CONFIG_PM=y
CONFIG_PM_DEVICE=y
CONFIG_SYS_CLOCK_TICKS_PER_SEC=1000