# Seri haberleşme
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

# UART Interrupt sürücüsü 
CONFIG_UART_INTERRUPT_DRIVEN=y

#adc sürücüsü
CONFIG_ADC=y

#ı2c sürücüsü
CONFIG_I2C=y

#metin için gerekliymiş
CONFIG_CBPRINTF_FP_SUPPORT=y
